trainer:
  optimizer:
    lr: 0.0003
    weight_decay: 0.001

dataset:
  train:
    transforms:
      crop_type: 'random_pad'
      crop_size: 32
      pad_size: 4
      horizontal_flip: true
    shuffle: false

defaults:
- _continual
- dataset: cifar100
- model: nature_mlp
- trainer: base
- _self_